services:
  conduit:
    image: ghcr.io/conduitio/conduit:v0.13.1
    networks:
      - benchi
    ports:
      - '8081:8080'
    environment:
      CONDUIT_LOG_FORMAT: json

networks:
  benchi:
    external: true
