version: "2.2"
pipelines:
  - id: kafka-to-kafka
    status: running
    connectors:
      - id: benchi-in
        type: source
        plugin: builtin:kafka
        settings:
          servers: "benchi-kafka:9092"
          topics: "benchi-in"
          readFromBeginning: "true"
          groupID: "benchi"

      - id: benchi-out
        type: destination
        plugin: builtin:kafka
        settings:
          servers: "benchi-kafka:9092"
          topic: 'benchi-out'
